### ISSUE TITLE
Customized Jupyter Lab Parameters

### ISSUE THREAD

**Issue by rileymcdowell** [dask/dask-docker#124]
I'm using your fantastic dask notebook image, thanks for creating it!

I would like to pass some extra parameters to the notebook as command line arguments. This doesn't seem to be possible using the standard `prepare.sh` script, so I need to customize the image with an additional layer to enable this.

1. Did I miss something and there is a good way to pass parameters without creating another image layer?
2. If not, is there any interest here in a pull request to support this? An easy implementation would be an environment variable, say `JUPYTERLAB_ARGS`  that contains any additional command line args to be passed through or an empty string otherwise.

The line of code in question: [link](https://github.com/dask/dask-docker/blob/ec72be77d9ef9aa80e82566076fbfc5f0e1cbd81/notebook/prepare.sh#L32)

**Comment by jacobtomlinson** [comment]
Thanks for raising this @rileymcdowell!

One solution would be to configure any options via a [Jupyter config file](https://jupyter-notebook.readthedocs.io/en/stable/config.html) and expose that to the container as a volume.

Alternatively, we could definitely allow for passing in extra CLI args via an environment variable. Do you have any interest in contributing this?

**Comment by rileymcdowell** [comment]
No problem, I can make a PR for you to review.

**Comment by rileymcdowell** [comment]
This ended up a little bigger than I hope. Here's what I did.

1.Added `JUPYTERLAB_ARGS`` variable, as discussed
2. Added some entries to the README to show some of the supported environment variables.
3. Modified the way the `start.sh` script works

It's this third one that I was a little unsure about. With what's currently in master, the notebook image is actually dropping me to a bash prompt. [This particular commit](https://github.com/dask/dask-docker/commit/b92cc91fd3ae3f771edd841ec865ab740af05945) seems to be the culprit. I left some comments there. Let me know what you think about this. It might be preferable to address this third bullet separately from this issue. As is, I attempted to resolve all of this with one MR.

FYI, I tested all this with the following docker-compose file - it all seems to work the way I expect.

```yaml
version: "3.7"

services:
  dask-notebook:
    image: daskdev/dask-notebook:latest
    environment:
      - JUPYTERLAB_ARGS=--NotebookApp.open_browser=False --NotebookApp.token='' --NotebookApp.password_required=False
      - EXTRA_APT_PACKAGES=dns-utils
      - EXTRA_PIP_PACKAGES=deap
      - EXTRA_CONDA_PACKAGES=pytest
    ports:
      - "8888:8888"
```
