### ISSUE TITLE
Jupyter Lab permission denied errors on creating notebook

### ISSUE THREAD

**Issue by haf** [dask/dask-docker#193]
**What happened**:

Installing with default options and doing a `FROM` custom dockerfile leads to permission denied errors when clicking "Notebook" in the UI.

**What you expected to happen**:

Since I'm just extending your notebook, there should be no permission denied errors.

**Minimal Complete Verifiable Example**:

```yaml
---
# Source: dask/templates/dask-jupyter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-jupyter

  labels:
    app: dask
    component: jupyter

spec:
  selector:
    matchLabels:
      app: dask
      component: jupyter

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: dask
        component: jupyter

    spec:
      serviceAccountName: dask-jupyter

      containers:
      - name: dask-jupyter
        image: example/dask-notebook # this is the specific image built from the Dockerfile below
        # image: daskdev/dask-notebook:2021.10.0

        ports:
        - name: http-web
          containerPort: 8888

        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 4Gi
            cpu: 1000m

        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/jupyter

        env:
        - name: DASK_SCHEDULER_ADDRESS
          value: dask-scheduler:8786

      volumes:
      - name: config-volume
        configMap:
          name: dask-jupyter-config
```

With this Dockerfile:

```Dockerfile
# https://github.com/dask/dask-docker/blob/main/base/Dockerfile
# https://docs.dask.org/en/latest/how-to/deploy-dask/docker.html
# https://github.com/dask/dask-docker/blob/main/notebook/Dockerfile

FROM daskdev/dask-notebook:2021.10.0-py3.8

USER $NB_USER

WORKDIR /opt/app

ENV POETRY_VERSION=1.1.11

RUN pip install "poetry==$POETRY_VERSION"

COPY --chown=1000:100 poetry.lock pyproject.toml postinstall.py ./
COPY --chown=1000:100 infer ./infer

RUN POETRY_VIRTUALENVS_CREATE=false poetry install --no-interaction --no-ansi
RUN python postinstall.py

ENV PYTHONPATH=/opt/app/infer/mmm:/opt/app/infer/prefect-utils

# test 1: import mmm
RUN python -c 'import mmm'

# test 2: import further in
RUN python -c 'from mmm.data.fetching import METRICS_COL_NAMES'

USER root
```

**Anything else we need to know?**:

This is the error on the frontend:

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/193115/139205076-b448f2d2-4376-4de1-8568-9704aba0d204.png">

This happens when you click the button to create a notebook.

The server logs:

```
dask-jupyter-796c448d99-b98qc dask-jupyter [W 2021-10-28 07:07:41.642 ServerApp] Permission denied: Untitled.ipynb
dask-jupyter-796c448d99-b98qc dask-jupyter [W 2021-10-28 07:07:41.643 ServerApp] 403 POST /api/contents?1635404861591 (127.0.0.1) 27.93ms referer=http://localhost:8888/lab
```

Aside: I don't know if using `pip` together with the _conda_ and _mamba_ is even possible: https://github.com/dask/dask-docker/blob/main/notebook/Dockerfile#L28-L49
Aside: I can't access the notebook from its public domain; the page goes all white and I get lots of 404's

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/193115/139205520-be0588a6-f24c-41fa-97b6-ccd38ae88298.png">

**Environment**:

- Dask version: see deployment above
- Python version: see dockerfile above
- Operating System: CoS / Linux
- Install method (conda, pip, source): pip
