### ISSUE TITLE
update_graph() got an unexpected keyword argument 'actors'

### ISSUE THREAD

**Issue by lukejpreston** [dask/dask-docker#35]
I am not sure what would be causing the following error as I haven't changed anything, it just seems to have started happening after rebuilding my images

```
dask-scheduler_1  | distributed.core - ERROR - update_graph() got an unexpected keyword argument 'actors'
dask-scheduler_1  | Traceback (most recent call last):
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 321, in handle_comm
dask-scheduler_1  |     result = yield result
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
dask-scheduler_1  |     value = future.result()
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
dask-scheduler_1  |     yielded = self.gen.send(value)
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 1923, in add_client
dask-scheduler_1  |     yield self.handle_stream(comm=comm, extra={'client': client})
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
dask-scheduler_1  |     value = future.result()
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
dask-scheduler_1  |     yielded = self.gen.send(value)
dask-scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 375, in handle_stream
dask-scheduler_1  |     handler(**merge(extra, msg))
dask-scheduler_1  | TypeError: update_graph() got an unexpected keyword argument 'actors'
dask-scheduler_1  | distributed.scheduler - INFO - Receive client connection: Client-b183835c-d2e2-11e8-8001-0242ac130007
dask-scheduler_1  | distributed.core - INFO - Starting established connection
```

here is my docker compose file

```yaml
version: '3.3'
services:
    dask-scheduler:
        image: daskdev/dask:0.18.1
        command: ["dask-scheduler"]
        volumes:
            - ./mnt:/mnt
        env_file:
            - .env
            - .env.local
        ports:
            - 8786:8786
            - 8787:8787
    worker:
        image: daskdev/dask:0.18.1
        command: ["dask-worker", "dask-scheduler:8786"]
        volumes:
            - ./mnt:/mnt
        env_file:
            - .env
            - .env.local
        depends_on:
            - dask-scheduler
```

I have tried deleting all images, containers and networks and then rebuilding everything but then when I start up my service I get the error above. I haven't changed my code and get access to the client with the following

```python
def get_client() -> Client:
    client = Client('dask-scheduler:8786')
    while not client.scheduler_info()['workers']:
        print('Workers are asleep')
        time.sleep(1)
    client.restart()
    client.upload_file('/usr/app/src/hash.py')
    return client
```

I have taken the all the code after `client` out, it seems to make no difference, it seems to throw this error the moment I try to use the client, all the `futures` return as `cancelled`

here is example code I am running which seems to trigger my error

```python
futures = client.map(run_hash(dir), batches)

for future in as_completed(futures):
    if future.status == 'finished':
        files += future.result()
    else:
        print('{} - {}'.format(future.status, future.exception()))
```

I am using `0.18.1` because the helm charts currently use dask version `0.18.1`

any help would be appreciated
