### ISSUE TITLE
APT install part doesn't work

### ISSUE THREAD

**Issue by gaiar** [dask/dask-docker#59]
Trying to install `build-essential` package for some of pip requirements, can't pass-through because of that error. 

```+ '[' build-essential ']'
EXTRA_APT_PACKAGES environment variable found.  Installing.
+ echo 'EXTRA_APT_PACKAGES environment variable found.  Installing.'
+ apt update -y

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
+ apt install -y build-essential

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?```

**Comment by TomAugspurger** [comment]
Hmm, this just worked

```
$ docker run -it --rm -e "EXTRA_APT_PACKAGES=vim" daskdev/dask
+ '[' vim ']'
+ echo 'EXTRA_APT_PACKAGES environment variable found.  Installing.'
EXTRA_APT_PACKAGES environment variable found.  Installing.
+ apt update -y
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [503 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.4 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Fetched 7919 kB in 2s (3937 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ apt install -y vim
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  vim-common vim-runtime xxd
Suggested packages:
  ctags vim-doc vim-scripts
The following NEW packages will be installed:
  vim vim-common vim-runtime xxd
0 upgraded, 4 newly installed, 0 to remove and 11 not upgraded.
Need to get 6734 kB of archives.
After this operation, 31.1 MB of additional disk space will be used.
Get:1 http://security.debian.org/debian-security stretch/updates/main amd64 xxd amd64 2:8.0.0197-4+deb9u3 [132 kB]
Get:2 http://security.debian.org/debian-security stretch/updates/main amd64 vim-common all 2:8.0.0197-4+deb9u3 [159 kB]
Get:3 http://security.debian.org/debian-security stretch/updates/main amd64 vim-runtime all 2:8.0.0197-4+deb9u3 [5409 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 vim amd64 2:8.0.0197-4+deb9u3 [1034 kB]
Fetched 6734 kB in 0s (8682 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package xxd.
(Reading database ... 10409 files and directories currently installed.)
Preparing to unpack .../xxd_2%3a8.0.0197-4+deb9u3_amd64.deb ...
Unpacking xxd (2:8.0.0197-4+deb9u3) ...
Selecting previously unselected package vim-common.
Preparing to unpack .../vim-common_2%3a8.0.0197-4+deb9u3_all.deb ...
Unpacking vim-common (2:8.0.0197-4+deb9u3) ...
Selecting previously unselected package vim-runtime.
Preparing to unpack .../vim-runtime_2%3a8.0.0197-4+deb9u3_all.deb ...
Adding 'diversion of /usr/share/vim/vim80/doc/help.txt to /usr/share/vim/vim80/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim80/doc/tags to /usr/share/vim/vim80/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:8.0.0197-4+deb9u3) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a8.0.0197-4+deb9u3_amd64.deb ...
Unpacking vim (2:8.0.0197-4+deb9u3) ...
Setting up xxd (2:8.0.0197-4+deb9u3) ...
Setting up vim-common (2:8.0.0197-4+deb9u3) ...
Setting up vim-runtime (2:8.0.0197-4+deb9u3) ...
Setting up vim (2:8.0.0197-4+deb9u3) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
no environment.yml
+ '[' '' ']'
+ '[' '' ']'
+ exec
```

What command are you running?

**Comment by gaiar** [comment]
I running it via k8s helm install with env variables defined.

**Comment by gaiar** [comment]
could it be related to the image version? I'm running 2.3.0

**Comment by TomAugspurger** [comment]
I'm not sure. Is  the command from helm running as a different user?

**Comment by quasiben** [comment]
Can you give us your helm command ?  Which helm chart are you using ?

**Comment by gaiar** [comment]
Command:
`helm install --name applift-dask -f values.yaml stable/dask`

config:
```
# nameOverride: dask
# fullnameOverride: dask

scheduler:
  name: scheduler
  image:
    repository: "daskdev/dask"
    tag: "2.3.0"
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: "2.3.0"
    pullPolicy: IfNotPresent
  replicas: 3
  aptPackages: >-
  default_resources:  # overwritten by resource limits if they exist
    cpu: 2
    memory: "4GiB"
  env:
    - name: EXTRA_APT_PACKAGES
      value: build-essential
    - name: EXTRA_CONDA_PACKAGES
      value: cython google-cloud-bigquery pandas scikit-learn pyarrow spacy dask-ml -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: sparse_dot_topn --upgrade
  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 3G
    # requests:
    #   cpu: 1
    #   memory: 3G

jupyter:
  name: jupyter
  enabled: true
  image:
    repository: "daskdev/dask-notebook"
    tag: "2.3.0"
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 80
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'  # 'dask'
  env:
    - name: EXTRA_APT_PACKAGES
      value: build-essential
    - name: EXTRA_CONDA_PACKAGES
      value: cython google-cloud-bigquery pandas scikit-learn pyarrow spacy dask-ml -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: sparse_dot_topn --upgrade
  resources: {}
    # limits:
    #   cpu: 2
    #   memory: 6G
    # requests:
    #   cpu: 2
    #   memory: 6G
```

**Comment by gaiar** [comment]
and here is more full log:

```
+ '[' build-essential ']'
EXTRA_APT_PACKAGES environment variable found.  Installing.
+ echo 'EXTRA_APT_PACKAGES environment variable found.  Installing.'
+ apt update -y

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
+ apt install -y build-essential

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

**Comment by gaiar** [comment]
I was able to resolve installation with adding:
```
  env:
    - name: GRANT_SUDO
      value: "yes"
```
but after that I'm getting errors like:
`[W 09:19:17.376 LabApp] [Errno 30] Read-only file system: '/home/jovyan/.jupyter/lab'`

**Comment by TomAugspurger** [comment]
Can you figure out what user the `apt-get install` commands are running as?

IMO, at this point you might want to build your own docker image that includes `build-essential`, and use that as your image.

**Comment by gaiar** [comment]
I've solved the issue by rebuilding pip package into conda package. But now I'm having troubles with the issue referenced here - https://github.com/helm/charts/issues/13124. Any ideas on solving it?

**Comment by gaiar** [comment]
I've managed to get rid of that error by cloning helm chart repo and changing values to:
```
volumeMounts:
            - name: config-volume
              mountPath: /home/jovyan/.jupyter/jupyter_notebook_config.py
              subPath: jupyter_notebook_config.py
```
